"""Tool generator — packages the winning pipeline as an installable CLI tool."""

from __future__ import annotations

import logging
from pathlib import Path
from textwrap import dedent
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from endforecast.engine.pipeline import Pipeline

logger = logging.getLogger(__name__)


class ToolGenerator:
    def __init__(self, pipeline: "Pipeline") -> None:
        self.pipeline = pipeline

    def export(self, output_dir: str | Path) -> Path:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        pkg_dir = output_dir / "predictor"
        pkg_dir.mkdir(exist_ok=True)
        models_dir = output_dir / "models"
        models_dir.mkdir(exist_ok=True)

        import joblib
        joblib.dump(self.pipeline._model, models_dir / "model.bin")
        for name, artifact in self.pipeline._artifacts.items():
            joblib.dump(artifact, models_dir / f"{name}.pkl")

        cfg = self.pipeline.config
        tool_name = cfg.pipeline_id.replace("_", "-")

        (output_dir / "pyproject.toml").write_text(dedent(f"""[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "{tool_name}"
version = "{cfg.version}"
description = "Auto-generated predictor by EndForecast"
requires-python = ">=3.10"
dependencies = ["pandas>=2.0", "numpy>=1.24", "scikit-learn>=1.3", "joblib>=1.3"]

[project.scripts]
endforecast-predict = "predictor.cli:main"
"""))
        (pkg_dir / "__init__.py").write_text(
            f'"""Auto-generated by EndForecast: {cfg.pipeline_id}"""\n__version__ = "{cfg.version}"\n'
        )
        (pkg_dir / "cli.py").write_text(dedent("""\
import argparse, pandas as pd
from predictor.model import Model

def main():
    p = argparse.ArgumentParser(description="EndForecast Predictor")
    p.add_argument("--input", "-i", required=True)
    p.add_argument("--output", "-o", default=None)
    args = p.parse_args()
    data = pd.read_csv(args.input)
    pred = Model().predict(data)
    result = data.copy()
    result["prediction"] = pred
    if args.output:
        result.to_csv(args.output, index=False)
    else:
        print(result.to_string())
"""))
        (pkg_dir / "model.py").write_text(self._generate_model_code())

        self._write_readme(output_dir)
        return output_dir

    def _generate_model_code(self) -> str:
        """Generate the model module with embedded refinement logic."""
        cfg = self.pipeline.config
        refine_code = self._generate_refinement_code()
        return dedent(f'''
"""Forend auto-generated prediction model."""

import joblib
import numpy as np
import pandas as pd

class Model:
    """Auto-generated {cfg.model.get("type", "unknown")} model by Forend."""

    def __init__(self, model_dir: str = "models"):
        import os
        self._model = joblib.load(os.path.join(model_dir, "model.bin"))

    def predict(self, df: pd.DataFrame) -> np.ndarray:
        raw = self._model.predict(df)
        return self._refine(raw)

    def _refine(self, raw: np.ndarray) -> np.ndarray:
{self._indent(refine_code, 8)}
''')

    def _generate_refinement_code(self) -> str:
        """Generate the _refine() method body from the pipeline's refinement config."""
        refinement = self.pipeline.config.refinement
        if not refinement or refinement.get("type", "none") == "none":
            return "return raw"

        params = refinement.get("params", {})
        method = params.get("method", "none")

        if method == "residual_correction":
            bias = params.get("bias_correction", 0)
            return f"return raw + {bias}"
        if method == "threshold_optimization":
            t = params.get("optimized_threshold", 0.5)
            return f"return (raw >= {t}).astype(float)"
        if method == "statistical":
            bias = params.get("bias_correction", 0)
            lo = params.get("clip_lower", float("-inf"))
            hi = params.get("clip_upper", float("inf"))
            if bias == 0 and lo == float("-inf") and hi == float("inf"):
                return "return raw"
            lines = [f"corrected = raw + {bias}" if bias != 0 else "corrected = raw"]
            lines.append(f"return np.clip(corrected, {lo}, {hi})")
            return "\n".join(lines)
        if method == "none":
            return "return raw"
        return "return raw"

    @staticmethod
    def _indent(code: str, spaces: int) -> str:
        prefix = " " * spaces
        return "\n".join(prefix + line if line.strip() else line for line in code.split("\n"))

    def _write_readme(self, output_dir: Path) -> None:
        cfg = self.pipeline.config
        refine_note = ""
        if cfg.refinement and cfg.refinement.get("type", "none") != "none":
            method = cfg.refinement.get("params", {}).get("method", cfg.refinement.get("type", ""))
            refine_note = f"\n- Refinement: {method} (embedded)"
        (output_dir / "README.md").write_text(
            f"# {cfg.pipeline_id}\n\n"
            f"```bash\npip install -e .\nendforecast-predict --input new_data.csv --output predictions.csv\n```\n"
            f"- Task: {cfg.task_type}\n"
            f"- Model: {cfg.model.get('type', 'unknown')}{refine_note}\n"
        )