"""Experiment Planner Agent — designs multi-model comparison plans.

Architecture: The Planner is the DECISION layer for experiment design.
When LLM is available, model/feature/preprocessing choices are driven
by the PLANNER_SYSTEM_PROMPT in prompts.py and passed via llm_suggestions.
When LLM is NOT available, a sensible fallback is used.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Optional

from endforecast.agents.explorer import ExplorationReport
from endforecast.engine.trial import Trial
from endforecast.engine.router import Route

logger = logging.getLogger(__name__)


@dataclass
class ExperimentPlan:
    task_type: str
    description: str = ""
    trials: list[Trial] = field(default_factory=list)
    route: Optional[Route] = None
    # Whether this plan was generated by LLM (True) or fallback rules (False)
    llm_driven: bool = False

    @property
    def n_trials(self) -> int:
        return len(self.trials)

    def summary(self) -> str:
        source = "LLM" if self.llm_driven else "fallback"
        return (
            f"ExperimentPlan[{self.task_type}]: {self.n_trials} trials "
            f"| route={self.route.value if self.route else 'unknown'} "
            f"| source={source}"
        )


class ExperimentPlanner:
    """Generates experiment plans from exploration results.

    Two modes:
    - LLM-driven (primary): accepts llm_suggestions dict containing
      model names, features, preprocessing chosen by the LLM
    - Fallback (no LLM): uses sensible defaults based on task type

    Usage:
        >>> planner = ExperimentPlanner()
        >>> # LLM-driven
        >>> plan = planner.plan(report, route=Route.STANDARD,
        ...     llm_suggestions={"models": ["ridge","lightgbm","xgboost"],
        ...                     "features": ["lag_24","lag_168","hour"]})
        >>> # Fallback
        >>> plan = planner.plan(report, route=Route.FAST)
    """

    def plan(
        self,
        report: ExplorationReport,
        route: Route = Route.STANDARD,
        max_trials: int = 30,
        llm_suggestions: Optional[dict] = None,
    ) -> ExperimentPlan:
        """Design an experiment plan.

        Args:
            report: ExplorationReport from DataExplorer.
            route: Execution track (fast/standard/deep).
            max_trials: Maximum number of trials.
            llm_suggestions: Optional dict from LLM with keys:
                "models": [{"name": "ridge"}, {"name": "lightgbm"}, ...]
                "features": [["lag_24","hour"], ["lag_24","lag_168","hour"], ...]
                "preprocessing": [["standard_scaler"], ...]
                "rationale": "LLM's reasoning"

        Returns:
            ExperimentPlan ready for execution.
        """
        if llm_suggestions:
            return self._plan_from_llm(report, route, max_trials, llm_suggestions)
        return self._plan_fallback(report, route, max_trials)

    def _plan_from_llm(
        self, report: ExplorationReport, route: Route, max_trials: int,
        suggestions: dict,
    ) -> ExperimentPlan:
        """Build a plan from LLM suggestions."""
        models = suggestions.get("models", [{"name": "ridge"}])
        feature_combos = suggestions.get("features", [["hour", "day_of_week"]])
        preprocesses = suggestions.get("preprocessing", [[]])
        rationale = suggestions.get("rationale", "LLM-driven plan")

        trials: list[Trial] = []
        tid = 0
        for model_info in models:
            name = model_info["name"] if isinstance(model_info, dict) else model_info
            name_str = str(name)
            for preproc in preprocesses:
                for feats in feature_combos:
                    if tid >= max_trials:
                        break
                    trials.append(Trial(
                        id=f"T{tid + 1}",
                        preprocess=preproc,
                        features=feats if isinstance(feats, list) else [feats],
                        model=name_str,
                        model_params=model_info.get("params", {}) if isinstance(model_info, dict) else {},
                        cv_strategy=self._pick_cv(report),
                        task_type=report.task_type,
                        metric=report.suggested_metrics[0] if report.suggested_metrics else "mase",
                        hypothesis=rationale[:100] if tid == 0 else "",
                    ))
                    tid += 1

        logger.info("LLM-driven plan: %s trials (%s)", len(trials), rationale[:60])
        return ExperimentPlan(
            task_type=report.task_type,
            description=f"LLM-driven: {rationale[:100]}",
            trials=trials[:max_trials], route=route, llm_driven=True,
        )

    def _plan_fallback(
        self, report: ExplorationReport, route: Route, max_trials: int,
    ) -> ExperimentPlan:
        """Fallback plan when no LLM is available."""
        models = self._fallback_models(report, route)
        preprocesses = self._fallback_preprocess(report, route)
        feature_combos = self._fallback_features(report, route)

        trials: list[Trial] = []
        tid = 0
        for model_info in models:
            for preproc in preprocesses:
                for feats in feature_combos:
                    if tid >= max_trials:
                        break
                    trials.append(Trial(
                        id=f"T{tid + 1}",
                        preprocess=preproc,
                        features=feats,
                        model=model_info.get("name", "ridge"),
                        model_params=model_info.get("params", {}),
                        cv_strategy=self._pick_cv(report),
                        task_type=report.task_type,
                        metric=report.suggested_metrics[0] if report.suggested_metrics else "mase",
                    ))
                    tid += 1

        return ExperimentPlan(
            task_type=report.task_type,
            description=f"Fallback plan: {report.n_rows} rows",
            trials=trials[:max_trials], route=route, llm_driven=False,
        )

    # ── Fallback heuristics (used when no LLM) ──────────────────

    def _fallback_models(self, report: ExplorationReport, route: Route) -> list[dict]:
        """Sensible defaults: start with ridge, add tree models if budget allows."""
        all_m = {
            "classification": [
                {"name": "logistic"}, {"name": "lightgbm"}, {"name": "xgboost"}, {"name": "random_forest"},
            ],
            "regression": [
                {"name": "ridge"}, {"name": "lightgbm"}, {"name": "xgboost"}, {"name": "random_forest"},
            ],
            "timeseries": [
                {"name": "ridge"}, {"name": "lightgbm"}, {"name": "xgboost"}, {"name": "random_forest"},
            ],
        }
        task_models = all_m.get(report.task_type, all_m["regression"])
        if route == Route.FAST:
            return task_models[:2]
        elif route == Route.STANDARD:
            return task_models[:3]
        return task_models

    def _fallback_preprocess(self, report: ExplorationReport, route: Route) -> list[list[str]]:
        opts = [[], ["standard_scaler"]]
        if route == Route.FAST:
            return opts[:1]
        return opts

    def _fallback_features(self, report: ExplorationReport, route: Route) -> list[list[str]]:
        s = report.suggested_features
        if not s:
            return [[]]
        combos = [[]]
        if len(s) >= 2:
            combos.append(s[:2])
        if len(s) >= 4:
            combos.append(s[:4])
        return combos

    def _pick_cv(self, report: ExplorationReport) -> str:
        if report.task_type == "timeseries":
            return "rolling_window" if report.n_rows > 1000 else "expanding_window"
        return "kfold"